name: Iyaret 035 - CI/CD Workflow

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment to prevent artifact conflicts
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Deploy Pages Actual
        uses: actions/deploy-pages@v4
